### ISSUE TITLE
Include build and set up instructions

### ISSUE THREAD

**Issue by commandodev** [visi-lang/visi#13]
Hi,

I couldn't find any build instructions in the README. Are there any docs for building that I've missed?

I'm using cabal version 0.10.2 and ghc 7.0.4 and I got

```
Linking dist/build/visi/visi ...
ld: warning: could not create compact unwind for .LFB3: non-standard register 5 being saved in prolog
Undefined symbols for architecture i386:
  "_main", referenced from:
      start in crt1.10.6.o
     (maybe you meant: _Main_main2_closure, _Main_main7_info , _Main_main10_info , _Main_main11_srt , _ZCMain_main_info , _Main_main11_closure , _Main_main1_closure , _Main_main8_info , _Main_main11_info , _Main_main_srt , _Main_main9_closure , _Main_main10_closure , _ZCMain_main_srt , _Main_main1_info , _Main_main9_info , _Main_main8_closure , _Main_main7_closure , _Main_main_closure , _Main_main6_closure , _Main_main4_info , _Main_main1_srt , _Main_main5_closure , _Main_main4_srt , _ZCMain_main_closure , _Main_main4_closure , _Main_main7_srt , _Main_main9_srt , _Main_main_info , _Main_main6_info , _Main_main3_closure )
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status
cabal: Error: some packages failed to install:
Visi-0.1 failed during the building phase. The exception was:
ExitFailure 1
```

I understand from the dependency on ghc-iphone that my version of ghc might be too new, but it would be good to have a comprehensive "This is how you get set up" document.

Cheers - looks like a very interesting project!
Ben

**Comment by ghost** [comment]
With the same versions of cabal and ghc I got a similar error but with a different root cause.

oscar@natty:~/src/visi/visi/core/src$ cabal --version
cabal-install version 0.10.2
using version 1.10.2.0 of the Cabal library 
oscar@natty:~/src/visi/visi/core/src$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.0.4

oscar@natty:~/src/visi/visi/core/src$ cabal install --verbose
Reading available packages...
[...]
Linking dist/build/visi/visi ...
/usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/../../../crt1.o: In function `_start':
(.text+0x20): undefined reference to`main'
collect2: ld returned 1 exit status
cabal: Error: some packages failed to install:
Visi-0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by dpp** [comment]
Please see https://github.com/visi-lang/visi/wiki/build
